### ISSUE TITLE
Develop & Release

### ISSUE THREAD

**Issue by ennerperez** [SmartlyDressedGames/RocketMod#18]
Hi, Im glad to see you working on Rocket, I'm wondering if you can consideraste to create a develop branch please? or maybe using gitflow model?

Also it is possible to you to publish releases first here to be updated about changes specially for server owners and admins?

**Comment by SDGNelson** [comment]
Can you elaborate on your branching concern please?
Sure - I will mark the current commit as 4.9.3.2

**Comment by SDGNelson** [comment]
https://github.com/SmartlyDressedGames/RocketMod/releases/tag/v4.9.3.2

**Comment by ennerperez** [comment]
Thanks.
https://nvie.com/posts/a-successful-git-branching-model/
GG

**Comment by SDGNelson** [comment]
I guess it makes sense branching for this repository because there is community involvement. Will do going forward.

For my personal projects I usually only branch when working on a feature that might not make it into the next release because I am the only one working on them. For UE4 I have a branch to deal with merges between engine versions.
